version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: dish_match_bd_container
    environment:
      POSTGRES_DB: dish_match_bd
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_user -d dish_match_bd"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - dish-match-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  dish-match-network:
    driver: bridge
