CREATE TABLE dishes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)             NOT NULL,
    ingredients TEXT[]                   NOT NULL DEFAULT '{}',
    user_id     BIGINT                   NOT NULL,
    tags        TEXT[]                   NOT NULL DEFAULT '{}',
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE history
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT                   NOT NULL,
    dish_id BIGINT                   NOT NULL,
    eaten_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_history_dish
        FOREIGN KEY (dish_id) REFERENCES dishes (id) ON DELETE CASCADE
);

CREATE INDEX idx_dishes_user_id ON dishes (user_id);
CREATE INDEX idx_history_user_eaten_at ON history (user_id, eaten_at DESC);
CREATE INDEX idx_history_dish_id ON history (dish_id);