DROP TABLE IF EXISTS history;
DROP TABLE IF EXISTS dishes;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    telegram_id BIGINT PRIMARY KEY,
    created_at  TIMESTAMP WITH TIME ZONE,
    updated_at  TIMESTAMP WITH TIME ZONE
);


CREATE TABLE dishes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)             NOT NULL,
    ingredients TEXT[]                   NOT NULL DEFAULT '{}',
    tags        TEXT[]                   NOT NULL DEFAULT '{}',
    created_at  TIMESTAMP WITH TIME ZONE,
    updated_at  TIMESTAMP WITH TIME ZONE
);


CREATE TABLE history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT                   NOT NULL,
    dish_id     BIGINT                   NOT NULL,
    eaten_at    TIMESTAMP WITH TIME ZONE
);


CREATE INDEX idx_history_user_eaten_at
    ON history (telegram_id, eaten_at DESC);

CREATE INDEX idx_history_dish_id
    ON history (dish_id);